---
- hosts: db
  become: true
  tasks:
    - name: install mysql-server
      apt: name=mysql-server state=present update_cache=yes

    - name: install tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - python3-mysqldb
      
    - name: start mysql
      service: name=mysql state=started enabled=yes

    - name: ensure mysql listening on all ports
      lineinfile: dest=/etc/mysql/mysql.conf.d/mysql.cnf regexp=^bind-address
                  line="bind-address = 0.0.0.0"
      notify: restart mysql

    - name: ensure mysql listening on all ports for real
      lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp=^bind-address
                  line="bind-address = 0.0.0.0"
      notify: restart mysql

      
    - name: create demo database
      mysql_db: name=demo state=present

    - name: create mysql user
      mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present
      
  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
